service: isthmus-api

frameworkVersion: "=1.25.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline must be last in this list

custom:
  entry: lib/index.handler
  dynamodb:
    start:
      migrate: true
  # tables
  contentTableName: 'content-table-${self:provider.stage}'
  pageTableName: 'page-table-${self:provider.stage}'
  resourceTableName: 'resource-table-${self:provider.stage}'
  schemaTableName: 'schema-table-${self:provider.stage}'
  siteTableName: 'site-table-${self:provider.stage}'
  userTableName: 'user-table-${self:provider.stage}'
  widgetTableName: 'widget-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
#        "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USER_TABLE}"
        - { "Fn::GetAtt": ["UserDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
#        "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SITE_TABLE}"
        - { "Fn::GetAtt": ["SiteDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
#        "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PAGE_TABLE}"
        - { "Fn::GetAtt": ["PageDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
#        "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SCHEMA_TABLE}"
        - { "Fn::GetAtt": ["SchemaDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
#        "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.RESOURCE_TABLE}"
        - { "Fn::GetAtt": ["ResourceDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
#        "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.WIDGET_TABLE}"
        - { "Fn::GetAtt": ["WidgetDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
#        "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CONTENT_TABLE}"
        - { "Fn::GetAtt": ["ContentDynamoDBTable", "Arn"] }
  environment:
    CONTENT_TABLE: ${self:custom.contentTableName}
    PAGE_TABLE: ${self:custom.pageTableName}
    RESOURCE_TABLE: ${self:custom.resourceTableName}
    SCHEMA_TABLE: ${self:custom.schemaTableName}
    SITE_TABLE: ${self:custom.siteTableName}
    USER_TABLE: ${self:custom.userTableName}
    WIDGET_TABLE: ${self:custom.widgetTableName}

functions:
  app:
    handler: ${self:custom.entry}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getUser:
    handler: ${self:custom.entry}
    events:
      - http: 'GET /user/{poxy+}'
  createUser:
    handler: ${self:custom.entry}
    events:
      - http: 'POST /user'

resources:
  Resources:
    UserDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.userTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SchemaDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.schemaTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SiteDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.siteTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    PageDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.pageTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ResourceDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.resourceTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    WidgetDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.widgetTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ContentDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.contentTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
